
dist: trusty
sudo: false
language: node_js
node_js:
  - "12.14"
branches:
  only:
    - develop
    - master
notifications:
  email: false
cache:
  directories:
    - ./node_modules
install:
  - npm install
before_deploy:
  - npm run build -- --prod --base-href /angular-start-loader-demo/
  - cp dist/angular-start-loader-demo/index.html dist/angular-start-loader-demo/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-start-loader-demo
  on:
    branch: master