language: node_js
node_js:
  - "12.14"
branches:
  only:
    - develop
    - master
cache:
  directories:
    - ./node_modules
install:
  - npm install
script:
  - npm run buildprod
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master